# Generated by Django 4.0.1 on 2022-01-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('roll', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
    ]
